#Requires -Modules Microsoft.Graph.Applications
<#
.SYNOPSIS
    Creates an Azure AD application registration with Microsoft Graph delegated permissions for M365 Documentation.

.DESCRIPTION
    This script creates an Azure AD application with the required delegated permissions for reading
    Microsoft 365 configuration data. It generates a client secret and outputs the tenant ID, 
    application ID, and client secret value.

.EXAMPLE
    .\Create-M365DocApp.ps1
#>

[CmdletBinding()]
param()

# Connect to Microsoft Graph with required scopes
Write-Host "Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -Scopes "Application.ReadWrite.All" -NoWelcome -ErrorAction Stop
}
catch {
    Write-Error "Failed to connect to Microsoft Graph: $_"
    exit 1
}

# Get current context
$context = Get-MgContext
$tenantId = $context.TenantId

Write-Host "Connected to tenant: $tenantId" -ForegroundColor Green
Write-Host ""

# Define the application
$appName = "M365Documentation Reader"
$appDescription = "Application for reading Microsoft 365 configuration and policy data"

# Define required delegated permissions (Microsoft Graph)
$graphResourceId = "00000003-0000-0000-c000-000000000000" # Microsoft Graph

$delegatedPermissions = @(
    "AccessReview.Read.All",
    "Agreement.Read.All",
    "AppCatalog.Read.All",
    "Application.Read.All",
    "CloudPC.Read.All",
    "ConsentRequest.Read.All",
    "Device.Read.All",
    "DeviceManagementApps.Read.All",
    "DeviceManagementConfiguration.Read.All",
    "DeviceManagementManagedDevices.Read.All",
    "DeviceManagementRBAC.Read.All",
    "DeviceManagementServiceConfig.Read.All",
    "Directory.Read.All",
    "Domain.Read.All",
    "Organization.Read.All",
    "Policy.Read.All",
    "Policy.ReadWrite.AuthenticationMethod",
    "Policy.ReadWrite.FeatureRollout",
    "PrintConnector.Read.All",
    "Printer.Read.All",
    "PrinterShare.Read.All",
    "PrintSettings.Read.All",
    "PrivilegedAccess.Read.AzureAD",
    "PrivilegedAccess.Read.AzureADGroup",
    "PrivilegedAccess.Read.AzureResources",
    "User.Read"
)

Write-Host "Creating application registration..." -ForegroundColor Cyan

# Get Microsoft Graph Service Principal to retrieve permission IDs
$graphSp = Get-MgServicePrincipal -Filter "appId eq '$graphResourceId'"

# Map permission names to their IDs
$requiredResourceAccess = @()
$scopeList = @()

foreach ($permission in $delegatedPermissions) {
    $permissionObj = $graphSp.Oauth2PermissionScopes | Where-Object { $_.Value -eq $permission }
    
    if ($permissionObj) {
        $scopeList += @{
            Id = $permissionObj.Id
            Type = "Scope"
        }
        Write-Host "  ✓ Found permission: $permission" -ForegroundColor Gray
    }
    else {
        Write-Warning "Permission not found: $permission"
    }
}

$requiredResourceAccess = @{
    ResourceAppId = $graphResourceId
    ResourceAccess = $scopeList
}

# Create the application
try {
    $app = New-MgApplication -DisplayName $appName `
        -Description $appDescription `
        -SignInAudience "AzureADMyOrg" `
        -RequiredResourceAccess $requiredResourceAccess `
        -ErrorAction Stop
    
    Write-Host ""
    Write-Host "✓ Application created successfully!" -ForegroundColor Green
    Write-Host "  Display Name: $($app.DisplayName)" -ForegroundColor Gray
    Write-Host "  Application ID: $($app.AppId)" -ForegroundColor Gray
    Write-Host "  Object ID: $($app.Id)" -ForegroundColor Gray
}
catch {
    Write-Error "Failed to create application: $_"
    Disconnect-MgGraph | Out-Null
    exit 1
}

# Create a client secret (valid for 2 years)
Write-Host ""
Write-Host "Creating client secret..." -ForegroundColor Cyan

$secretDescription = "Generated by Create-M365DocApp.ps1"
$secretEndDate = (Get-Date).AddYears(2)

try {
    $passwordCredential = @{
        DisplayName = $secretDescription
        EndDateTime = $secretEndDate
    }
    
    $secret = Add-MgApplicationPassword -ApplicationId $app.Id -PasswordCredential $passwordCredential -ErrorAction Stop
    
    Write-Host "✓ Client secret created successfully!" -ForegroundColor Green
    Write-Host "  Expires: $($secret.EndDateTime)" -ForegroundColor Gray
}
catch {
    Write-Error "Failed to create client secret: $_"
    Write-Warning "Application was created but secret creation failed. You can create a secret manually in the Azure Portal."
    Disconnect-MgGraph | Out-Null
    exit 1
}

# Output the credentials
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Yellow
Write-Host "  APPLICATION CREDENTIALS" -ForegroundColor Yellow
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Yellow
Write-Host ""
Write-Host "Tenant ID:       " -NoNewline -ForegroundColor Cyan
Write-Host $tenantId -ForegroundColor White
Write-Host "Application ID:  " -NoNewline -ForegroundColor Cyan
Write-Host $app.AppId -ForegroundColor White
Write-Host "Client Secret:   " -NoNewline -ForegroundColor Cyan
Write-Host $secret.SecretText -ForegroundColor White
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Yellow
Write-Host ""
Write-Host "⚠️  IMPORTANT: Save the client secret now!" -ForegroundColor Red
Write-Host "   You won't be able to retrieve it again." -ForegroundColor Red
Write-Host ""

# Create a summary file
$outputFile = Join-Path $PSScriptRoot "M365DocApp-Credentials.txt"
$outputContent = @"
M365Documentation Application Credentials
==========================================
Created: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

Tenant ID:       $tenantId
Application ID:  $($app.AppId)
Client Secret:   $($secret.SecretText)
Secret Expires:  $($secret.EndDateTime)

IMPORTANT: Keep these credentials secure!

Next Steps:
-----------
1. An admin must consent to the delegated permissions in the Azure Portal
2. Navigate to: Azure Portal > Azure Active Directory > App registrations > $appName
3. Click "API permissions" > "Grant admin consent for [tenant]"
4. Use these credentials with the M365Documentation PowerShell module

"@

try {
    $outputContent | Out-File -FilePath $outputFile -Encoding UTF8 -Force
    Write-Host "✓ Credentials saved to: $outputFile" -ForegroundColor Green
    Write-Host ""
}
catch {
    Write-Warning "Could not save credentials to file: $_"
}

Write-Host "NEXT STEPS:" -ForegroundColor Yellow
Write-Host "1. An admin must grant consent to the permissions" -ForegroundColor White
Write-Host "2. In Azure Portal, go to: App registrations > $appName > API permissions" -ForegroundColor White
Write-Host "3. Click 'Grant admin consent for [your tenant]'" -ForegroundColor White
Write-Host ""

# Disconnect
Disconnect-MgGraph | Out-Null
Write-Host "✓ Complete!" -ForegroundColor Green
